fix download requirements & fix partition boot for akari ax810/at01
armarchindo/ULO-Builder pull request #10
Opened 2024-07-09 02:08 UTC by Haris131

2024-07-09 08:13 UTC, armarchindo requested changes
Matursuwun mbah haris,,
tolong bisa diedit dihilangkan fungsi 
```
    if [ $is_amlogic = true ];
```
jadi dihilangkan fungsi tersebut agar defaultnya bisa langsung partisinya menjadi vfat/fat32
```bash
    local is_allwinner=false
    echo $allwinner | grep -iq $device && is_allwinner=true

    if [ $is_amlogic = true ]; then
        mke2fs -F -q -t ext4 -L "BOOT" -m 0 ${loop}p1 >/dev/null 2>&1
    else
        mkfs.vfat -n "BOOT" ${loop}p1 >/dev/null 2>&1
    fi
    mke2fs -F -q -t ext4 -L "ROOTFS" -m 0 ${loop}p2 >/dev/null 2>&1

    #if [ "$device" = "s905x" ]; then
```
jadi
```bash

    local is_allwinner=false
    echo $allwinner | grep -iq $device && is_allwinner=true

    mkfs.vfat -n "BOOT" ${loop}p1 >/dev/null 2>&1
    mke2fs -F -q -t ext4 -L "ROOTFS" -m 0 ${loop}p2 >/dev/null 2>&1

    #if [ "$device" = "s905x" ]; then
```
sekali lagi matursuwun ya mbah haris hehe

2024-07-09 08:24 UTC, armarchindo commented
![image](https://github.com/armarchindo/ULO-Builder/assets/7347993/693dacdc-8d38-4d9b-9308-0725dd589c7b)
untuk file ini tidak bisa dihapus mbah,, soalnya kalau dihapus kemungkinan bakal error, soalnya kehapus semua dengan sub-foldernya

2024-07-10 05:12 UTC, Haris131 commented
Siap mbah.

Untuk folder core/root/lib/firmware kan kosong mbah, sedangkan di script ulo akan download file/folder firmware jika tidak ada folder core/root/lib/firmware

2024-07-10 14:30 UTC, nosignals commented
> Siap mbah.
> 
> Untuk folder core/root/lib/firmware kan kosong mbah, sedangkan di script ulo akan download file/folder firmware jika tidak ada folder core/root/lib/firmware

hooh mbah,, belom ganti metodenya wkwkwk, sebenernya mau tak buat if < file di directory firmware kosong, tapi belom sempat,,
thankyou mbah udah commit hehe

2024-07-10 14:30 UTC, merged